### ISSUE TITLE
把Windows下的按键也图标化怎么样？

### ISSUE THREAD

**Issue by JinSooo** [JinSooo/CheatSheet#5]
想把Windows下的按键也图标化，但是一方面Windows这些按键没有对应的图标，如果用Mac那一套加注释的话，感觉还是不是很好懂；但是又感觉Windows一个按键太长了

**Comment by NoahCodeGG** [comment]
不建议
1. windows 功能键本身并没有图标化（win 除外），对与无 mac 使用经验的 windows 用户来说学习成本过高了
2. 使用注释不方便，不能够一目了然，用户应该并不愿长时间停留
3. 按键太长可以考虑简写，如：Page Up -> PgUp
